### ISSUE TITLE
compiling (linking libraries) self-written example unclear

### ISSUE THREAD

**Issue by veethahavya-CU-cz** [Nicholaswogan/fortran-yaml-c#4]
first off - thanks for writing this!

i was able to follow your instructions and was able to run the tests successfully. now i am excited to implement this in my project, and it is a bit unclear to me what libraries i need to link to my program (apart from adding the include path to the folder containing the *.mod files).

unfortunately, i am not well versed with cmake and makefiles to infer that myself. could you please help me out here?

**Comment by Nicholaswogan** [comment]
I'm excited you might find it useful! 

There are a few options, depending on what build system you want to use for your project. Are you OK with using CMake? Or do you want to use something else, like Meson, makefile, or just a simple bash build script which directly calls gfortran and gcc?

I personally really like CMake. It is hard to learn at first, but I think it is worth it. There is also the [CMake package manager](https://github.com/cpm-cmake/CPM.cmake), which makes it pretty easy to add dependencies to your project.

**Comment by veethahavya-CU-cz** [comment]
thank you for offering to help!

like you mentioned, CMake and CPM do have a pretty steep learning curve, but i am sure they are worth learning. maybe one day i will, but i lack the time for it now.

so, it would be helpful if you could brief me on how i can use the library via bas script(s).

so, i have already tried compiling the example included under tests (./tests/example.f90) using the following command:
`gfortran -I../build/modules  ../build/src/libfortran-yaml-c.a ../build/src/liblibyaml_interface.a  example.f90 -o example`
but that produces the following error:
```
/usr/bin/ld: /tmp/ccZxiKlD.o: warning: relocation against `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_dictionary' in read-only section `.text'
/usr/bin/ld: /tmp/ccZxiKlD.o: in function `main.0':
example.f90:(.text+0x27): undefined reference to `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_node'
/usr/bin/ld: example.f90:(.text+0x46): undefined reference to `__fortran_yaml_c_MOD___vtab_fortran_yaml_c_Yamlfile'
/usr/bin/ld: example.f90:(.text+0x9b): undefined reference to `__fortran_yaml_c_MOD_yamlfile_parse'
/usr/bin/ld: example.f90:(.text+0x13b): undefined reference to `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_dictionary'
/usr/bin/ld: example.f90:(.text+0xa90): undefined reference to `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_list_item'
/usr/bin/ld: example.f90:(.text+0xacd): undefined reference to `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_scalar'
/usr/bin/ld: example.f90:(.text+0xb7f): undefined reference to `__fortran_yaml_c_types_MOD___vtab_fortran_yaml_c_types_Type_list_item'
/usr/bin/ld: example.f90:(.text+0xc2f): undefined reference to `__fortran_yaml_c_MOD___final_fortran_yaml_c_Yamlfile'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

**Comment by Nicholaswogan** [comment]
The correct command should be (after building with cmake)

```sh
gfortran example.f90 -o example \
-I../build/modules/ \
-L../build/src/ \
-I../build/_deps/libyaml-src/include/ \
-L../build/_deps/libyaml-build/ \
-lfortran-yaml-c \
-llibyaml_interface \
-lyaml
```

**Comment by veethahavya-CU-cz** [comment]
perfect, that worked! thank you :)

may i recommend listing the include dirs and libraries to be linked for execution in the readme? would be helpful
